services:
  conectaai-db:
    image: postgres:14
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_SSL_MODE=require
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.ssl/postgres:/etc/postgresql/ssl
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - conectaai-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/etc/postgresql/ssl/server.crt
               -c ssl_key_file=/etc/postgresql/ssl/server.key
               -c ssl_prefer_server_ciphers=on
               -c ssl_min_protocol_version=TLSv1.2
               -c ssl_ciphers=HIGH:!aNULL
               -c password_encryption=scram-sha-256
               -c hba_file=/etc/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=rafael@volvecare.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    secrets:
      - pgadmin_email
      - pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - conectaai-network
    ports:
      - "81:80"
    depends_on:
      - conectaai-db
    restart: unless-stopped      

  conectaai-shop:
    build:
      context: ./next
    secrets:
      - strapi_admin_client_preview_secret
    environment:
      - WEBSITE_URL=http://conectaai-shop:3000
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://conectaai-core:1337
      - PREVIEW_SECRET_FILE=/run/secrets/strapi_admin_client_preview_secret
      - NODE_ENV=production
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads      
    ports:
      - "3000:3000"
    depends_on:
      - conectaai-core
    networks:
      - conectaai-network
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  conectaai-core:
    build:
      context: ./strapi
    secrets: 
      - app_keys
      - api_token_salt
      - admin_jwt_secret
      - transfer_token_salt
      - jwt_secret
      - strapi_admin_client_preview_secret
      - database_username
      - database_password
      - database_name
      - pgdatabase
      - pguser
      - pgpassword
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      NODE_ENV: production
      APP_KEYS_FILE: /run/secrets/app_keys
      API_TOKEN_SALT_FILE: /run/secrets/api_token_salt
      ADMIN_JWT_SECRET_FILE: /run/secrets/admin_jwt_secret
      TRANSFER_TOKEN_SALT_FILE: /run/secrets/transfer_token_salt
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      STRAP_ADMIN_CLIENT_URL: http://conectaai-shop:3000
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET_FILE: /run/secrets/strapi_admin_client_preview_secret
      STRAPI_TELEMETRY_DISABLED: true
      DATABASE_CLIENT: postgres
      DATABASE_SCHEMA: public
      DATABASE_NAME_FILE: /run/secrets/database_name
      DATABASE_USERNAME_FILE: /run/secrets/database_username
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      DATABASE_HOST: conectaai-db
      DATABASE_PORT: 5432
      DATABASE_SSL: true
      DATABASE_SSL_REJECT_UNAUTHORIZED: false
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
      DATABASE_SSL_CERT: /etc/strapi/postgres/ssl/server.crt
      DATABASE_SSL_KEY: /etc/strapi/postgres/ssl/server.key
      PGUSER_FILE: /run/secrets/pguser
      PGDATABASE_FILE: /run/secrets/pgdatabase
      PGPASSWORD_FILE: /run/secrets/pgpassword
    volumes: 
      - ./.ssl/postgres:/etc/strapi/postgres/ssl
    ports: 
      - "1337:1337"
    depends_on:
      - conectaai-db
    networks:
      - conectaai-network
    #restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    secrets:
      - nginx_ssl_crt
      - nginx_ssl_key
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.ssl/nginx:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    environment:    
      SSL_CERT_FILE: /etc/nginx/ssl/server.crt
      SSL_KEY_FILE: /etc/nginx/ssl/server.key
    depends_on:
      - conectaai-shop
      - conectaai-core
    networks:
      - conectaai-network
    #restart: always

networks:
  conectaai-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local    

secrets:
  app_keys:
    file: ./.secrets/app_keys
  api_token_salt:
    file: ./.secrets/api_token_salt
  admin_jwt_secret:
    file: ./.secrets/admin_jwt_secret
  transfer_token_salt:
    file: ./.secrets/transfer_token_salt
  jwt_secret:
    file: ./.secrets/jwt_secret
  strapi_admin_client_preview_secret:
    file: ./.secrets/strapi_admin_client_preview_secret
  database_password:
    file: ./.secrets/postgres_password
  database_username:
    file: ./.secrets/postgres_user
  database_name:
    file: ./.secrets/postgres_db
  pgpassword:
    file: ./.secrets/postgres_password
  pguser:
    file: ./.secrets/postgres_user
  pgdatabase:
    file: ./.secrets/postgres_db
  postgres_password:
    file: ./.secrets/postgres_password
  postgres_db:
    file: ./.secrets/postgres_db
  postgres_user:
    file: ./.secrets/postgres_user
  postgres_ssl_crt:
    file: ./.ssl/postgres/server.crt
  postgres_ssl_key:
    file: ./.ssl/postgres/server.key
  nginx_ssl_crt:
    file: ./.ssl/nginx/server.crt
  nginx_ssl_key:
    file: ./.ssl/nginx/server.key
  pgadmin_email:
    file: ./.secrets/pgadmin_email
  pgadmin_password:
    file: ./.secrets/pgadmin_password
