version: '3.8'

services:
  conectaai-db:
    image: postgres:14
    container_name: conectaai-db
    secrets:
      - postgres_password
      - postgres_ssl_cert
      - postgres_ssl_key
    environment:
      POSTGRES_DB: strapidb
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conectaai-network
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "strapi"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/run/secrets/postgres_ssl_cert
               -c ssl_key_file=/run/secrets/postgres_ssl_key

  conectaai-shop:
    build:
      context: ./strapi
    secrets:
      - strapi_admin_client_preview_secret
    environment:
      - WEBSITE_URL=http://conectaai-shop:3000
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://conectaai-core:1337
      - PREVIEW_SECRET_FILE=/run/secrets/strapi_admin_client_preview_secret
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads      
    ports:
      - "3000:3000"
    depends_on:
      - conectaai-core
    networks:
      - conectaai-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  conectaai-core:
    build:
      context: ./nextjs
    secrets: 
      - app_keys
      - api_token_salt
      - admin_jwt_secret
      - transfer_token_salt
      - jwt_secret
      - strapi_admin_client_preview_secret
      - database_username
      - database_password
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      NODE_ENV: production
      APP_KEYS_FILE: /run/secrets/app_keys
      API_TOKEN_SALT_FILE: /run/secrets/api_token_salt
      ADMIN_JWT_SECRET_FILE: /run/secrets/admin_jwt_secret
      TRANSFER_TOKEN_SALT_FILE: /run/secrets/transfer_token_salt
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      STRAP_ADMIN_CLIENT_URL: http://conectaai-shop:3000
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET_FILE: /run/secrets/strapi_admin_client_preview_secret
      DATABASE_CLIENT: postgres
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
      DATABASE_HOST: conectaai-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_SCHEMA: public
      DATABASE_SSL: true
      DATABASE_SSL_REJECT_UNAUTHORIZED: true
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
    ports: 
      - "1337:1337"
    depends_on:
      - conectaai-db
    networks:
      - conectaai-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    secrets:
      - nginx_ssl_cert
      - nginx_ssl_key
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
      - '443:443'
    environment:    
      SSL_CERT_FILE: /run/secrets/nginx_ssl_cert
      SSL_KEY_FILE: /run/secrets/nginx_ssl_key
    depends_on:
      - conectaai-shop
      - conectaai-core
    networks:
      - conectaai-network
    restart: always

networks:
  conectaai-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

secrets:
  app_keys:
    file: ./.secrets/app_keys
  api_token_salt:
    file: ./.secrets/api_token_salt
  admin_jwt_secret:
    file: ./.secrets/admin_jwt_secret
  transfer_token_salt:
    file: ./.secrets/transfer_token_salt
  jwt_secret:
    file: ./.secrets/jwt_secret
  strapi_admin_client_preview_secret:
    file: ./.secrets/strapi_admin_client_preview_secret
  postgres_password:
    file: ./.secrets/postgres_password
  postgres_ssl_cert:
    file: ./.secrets/postgres_ssl_cert
  postgres_ssl_key:
    file: ./.secrets/postgres_ssl_key
  nginx_ssl_cert:
    file: ./.secrets/nginx_ssl_cert
  nginx_ssl_key:
    file: ./.secrets/nginx_ssl_key
